{% set name = "django-comments-xtd" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_comments_xtd-{{ version }}.tar.gz
  sha256: 6217c41ed398942c07a44374a308cd9bf541f5444d3d25b3eaae0447c4a66d48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=65.6.3
    - wheel
    - pip
  run:
    - python >=3.8
    - django >=3,<5.1
    - django-contrib-comments >=2.2,<2.3
    - djangorestframework >=3.12,<3.16
    - docutils
    - six
    - pytz

test:
  imports:
    - django_comments_xtd
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/django-comments-xtd
  summary: Django Comments Framework extension app with thread support, follow up notifications and email confirmations.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
