# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.10.12"

package:
  name: django-comments-xtd
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/django-comments-xtd/django_comments_xtd-${{ version }}.tar.gz
  sha256: 56f736a291e76a13c935202d1d6ea8ad9bf530707075ed128888d47499565a77

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.0,<7
    - django-contrib-comments >=2.2,<2.3
    - djangorestframework >=3.12,<3.18
    - docutils
    - pytz
    - six

tests:
  - python:
      imports:
        - django_comments_xtd
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Django Comments Framework extension app with thread support, follow up notifications and email confirmations.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/danirus/django-comments-xtd
  repository: https://github.com/danirus/django-comments-xtd
  documentation: https://django-comments-xtd.readthedocs.io
  description: |
    A Django Comments Framework extension app with thread support, follow-up
    notifications, mail confirmation before posting, like/dislike flags,
    moderation, comment-removal requests and a REST API.

extra:
  recipe-maintainers:
    - rxm7706
