# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-comments-xtd
  version: "2.10.9"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_comments_xtd-${{ version }}.tar.gz
  sha256: 24368664606b90b07dc08bd906b77b0c5ca6563c92fcb07c161f1ec793e6449c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4,<6
    - django-contrib-comments >=2.2,<2.3
    - djangorestframework >=3.12,<3.16
    - docutils
    - pytz
    - six

tests:
  - python:
      imports:
        - django_comments_xtd
      pip_check: true

      python_version: ${{ python_min }}.*

about:
  summary: Django Comments Framework extension app with thread support, follow up notifications and email confirmations.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: http://pypi.python.org/pypi/django-comments-xtd

extra:
  recipe-maintainers:
    - rxm7706
